### ISSUE TITLE
Exception caused by 80 character delimited X12

### ISSUE THREAD

**Issue by timjohnson6** [xlate/staedi#128]
**Describe the bug**
Attempting to parse the included X12 EDI 210 which is 80 character delimited is causing the following exception:
```
io.xlate.edi.internal.stream.tokenization.EDIException: EDIE003 - Invalid processing stateInvalid header segment at offset 105

	at io.xlate.edi.internal.stream.tokenization.Lexer.error(Lexer.java:403)
	at io.xlate.edi.internal.stream.tokenization.Lexer.dialectConfirmed(Lexer.java:395)
	at io.xlate.edi.internal.stream.tokenization.Lexer.parse(Lexer.java:225)
	at io.xlate.edi.internal.stream.StaEDIStreamReader.nextEvent(StaEDIStreamReader.java:155)
	at io.xlate.edi.internal.stream.StaEDIStreamReader.next(StaEDIStreamReader.java:187)
	at io.xlate.edi.internal.stream.StaEDIStreamReader.nextTag(StaEDIStreamReader.java:205)
```

**To Reproduce**
```
    EDIInputFactory factory = EDIInputFactory.newFactory();
    try (EDIStreamReader reader = factory.createEDIStreamReader(ediInputStream)) {
      while (reader.hasNext()) {
        reader.nextTag();
       }
     }
```
With the attached data file used in the `ediInputStream`

**Additional context**
[80char-edi210.txt](https://github.com/xlate/staedi/files/5311925/80char-edi210.txt)

**Comment by MikeEdgar** [comment]
@timjohnson6 , thanks for the report. Do you know ahead of time if the file wraps at 80 chars or is it critical for the parser to automatically detect it? This might be a candidate for a new configuration property in the case of the former.

**Comment by timjohnson6** [comment]
the format is constant between EDI providers.  so in that regard it can be known. I think ideally, if the parser can figure that out, that would be best.  I could do a work around, looking @ the file ahead of time to see the length of the lines and providing that to the parser.

**Comment by MikeEdgar** [comment]
Thanks @timjohnson6 . I'll take a look at this over the next few days. I'm familiar with the requirement, so definitely know it's not uncommon to encounter this.

**Comment by timjohnson6** [comment]
might be an easy fix to just replace all CR/LF and TABS (no printable characters) with nothing and process the file that way?

**Comment by MikeEdgar** [comment]
That's the way I'm leaning. I do not think it will be default behavior though. There will likely be a new option to turn it on, to preserve breaking users not opting in. In your case you would enable it always I think. Sound good?

**Comment by MikeEdgar** [comment]
@timjohnson6 - when `1.13.0` is released, this will be configurable by setting property `EDIInputFactory.EDI_IGNORE_EXTRANEOUS_CHARACTERS` to false on the factory. 

https://github.com/xlate/staedi/wiki/Reading-EDI-Data-(Configuration)#ignore-extraneous-characters
