### ISSUE TITLE
Help with JSON marshaling and unmarshaling

### ISSUE THREAD

**Issue by gadieichhorn** [xlate/staedi#129]
Thanks for the great lib.

I wonder if you have a JSON marshal and unmarshal example (apart from what I see in the tests) that shows how to convert EDI to JSON and back correctly for X12 and EDIFACT.

SC1
1. EDU -> JSON
2. JSON -> EDI
3. compare I got the same doc as started with.

SC2
1. JSON -> EDI
2. EDI -> JSON
3. compare JSON the same as started with.

I have taken a slightly different approach (from your JSON builder test)  and modeled each event as a Pojo/JSON 
I was hoping to visit each element and write it into the stream based on the structure (is a composite?) but I think I am missing something.

Expected
```
{"type":"interchange","header":{"type":"header","version":["UNOA","3"],"standard":"EDIFACT","delimiters":{"io.xlate.edi.stream.delim.segment":"'","io.xlate.edi.stream.delim.dataElement":"+","io.xlate.edi.stream.delim.release":"?","io.xlate.edi.stream.delim.decimal":".","io.xlate.edi.stream.delim.componentElement":":"}},"elements":[{"type":"segment","tag":"UNB","elements":[{"type":"composite","elements":[{"type":"data","value":"UNOA","occurrences":1},{"type":"data","value":"3","occurrences":1}]},{"type":"composite","elements":
```

Acctual
```
{"type":"interchange","header":{"type":"header","version":["UNOA","3"],"standard":"EDIFACT","delimiters":{"io.xlate.edi.stream.delim.segment":"'","io.xlate.edi.stream.delim.dataElement":"+","io.xlate.edi.stream.delim.release":"?","io.xlate.edi.stream.delim.decimal":".","io.xlate.edi.stream.delim.componentElement":":"}},"elements":[{"type":"segment","tag":"UNA","elements":[{"type":"data","value":" ","occurrences":1}]},{"type":"segment","tag":"UNB","elements":[{"type":"composite","elements":[{"type":"data","value":"UNOA","occurrences":1},{"type":"data","value":"3","occurrences":1}]}, 
```

What is a minimal EDI document I can build my tests with?

**Comment by MikeEdgar** [comment]
Hi @gadieichhorn - JSON has been something on my "to do" list for a while, but when it's added I want to make sure it's a format that easily supports conversion to and from EDI, just like you are attempting. I also want to ensure it's using a standard API (similar to how XML can be read/written in StAEDI) to avoid imposing any dependencies on users.

Have you looked at this Wiki page for ideas? https://github.com/xlate/staedi/wiki/Reading-EDI-Data-(JSON-Conversion)

The examples you in your comments look like they are truncated, can you post the full output? A good EDI document to test with might be a `CONTRL` transaction (I see you're using EDIFACT) with only a `UCI` segment.

**Comment by gadieichhorn** [comment]
Thanks @MikeEdgar 

I took one of your edi examples and run through my parser. 
Yes the X12 seemed to work fine for me.

did get strange errors on other files I tried:

`io.xlate.edi.internal.stream.tokenization.EDIException: EDIE003 - Invalid processing state: INVALID (previous: INITIAL); input: '*' at offset 0`

`java.nio.BufferOverflowException
	at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:665)`



here is the full test results:

```
Expected :{"type":"interchange","header":{"type":"header","version":["UNOA","3"],"standard":"EDIFACT","delimiters":{"io.xlate.edi.stream.delim.segment":"'","io.xlate.edi.stream.delim.dataElement":"+","io.xlate.edi.stream.delim.release":"?","io.xlate.edi.stream.delim.decimal":".","io.xlate.edi.stream.delim.componentElement":":"}},"elements":[{"type":"segment","tag":"UNB","elements":[{"type":"composite","elements":[{"type":"data","value":"UNOA","occurrences":1},{"type":"data","value":"3","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"5400110000009","occurrences":1},{"type":"data","value":"14","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"5013546107732","occurrences":1},{"type":"data","value":"14","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"010502","occurrences":1},{"type":"data","value":"1237","occurrences":1}]},{"type":"data","value":"2722166169492","occurrences":1},{"type":"composite","elements":[]},{"type":"data","value":"","occurrences":1},{"type":"data","value":"I","occurrences":1},{"type":"data","value":"0","occurrences":1},{"type":"data","value":"EANCOM","occurrences":1},{"type":"data","value":"1","occurrences":1}]},{"type":"group","name":"GROUP","elements":[{"type":"segment","tag":"UNG","elements":[{"type":"data","value":"ORDERS","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"5400110000009","occurrences":1},{"type":"data","value":"14","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"5013546107732","occurrences":1},{"type":"data","value":"14","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"010502","occurrences":1},{"type":"data","value":"1237","occurrences":1}]},{"type":"data","value":"1","occurrences":1},{"type":"data","value":"UN","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"D","occurrences":1},{"type":"data","value":"96A","occurrences":1},{"type":"data","value":"EAN008A","occurrences":1},{"type":"data","value":"IGNORED","occurrences":1}]}]},{"type":"transaction","elements":[{"type":"segment","tag":"UNH","elements":[{"type":"data","value":"1","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"ORDERS","occurrences":1},{"type":"data","value":"D","occurrences":1},{"type":"data","value":"96B","occurrences":1},{"type":"data","value":"UN","occurrences":1},{"type":"data","value":"EAN008B","occurrences":1}]}]},{"type":"segment","tag":"BGM","elements":[{"type":"data","value":"220","occurrences":1},{"type":"data","value":"C1441747","occurrences":1}]},{"type":"segment","tag":"DTM","elements":[{"type":"composite","elements":[{"type":"data","value":"137","occurrences":1},{"type":"data","value":"200105022200","occurrences":1},{"type":"data","value":"203","occurrences":1}]}]},{"type":"segment","tag":"FTX","elements":[{"type":"data","value":"PUR","occurrences":1},{"type":"data","value":"1","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"THIS IS AN EXAMPLE OF EDIFACT FILE.","occurrences":1}]},{"type":"segment","tag":"NAD","elements":[{"type":"data","value":"BY","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"5400110000009","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"9","occurrences":1}]}]},{"type":"segment","tag":"NAD","elements":[{"type":"data","value":"SU","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"5013546107732","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"9","occurrences":1}]},{"type":"data","value":"COMPANY ABC","occurrences":1}]},{"type":"segment","tag":"LIN","elements":[{"type":"data","value":"1","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"5400111864181","occurrences":1},{"type":"data","value":"EN","occurrences":1}]}]},{"type":"segment","tag":"PIA","elements":[{"type":"data","value":"1","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"8641800","occurrences":1},{"type":"data","value":"BP","occurrences":1}]}]},{"type":"segment","tag":"IMD","elements":[{"type":"data","value":"C","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"CU","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"9","occurrences":1},{"type":"data","value":"WIDGETS","occurrences":1}]}]},{"type":"segment","tag":"IMD","elements":[{"type":"data","value":"F","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"0.7066 EURO","occurrences":1}]}]},{"type":"segment","tag":"MEA","elements":[{"type":"data","value":"PD","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"LAY","occurrences":1},{"type":"data","value":"4","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"NAR","occurrences":1},{"type":"data","value":"6","occurrences":1}]}]},{"type":"segment","tag":"MEA","elements":[{"type":"data","value":"PD","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"ULY","occurrences":1},{"type":"data","value":"4","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"NAR","occurrences":1},{"type":"data","value":"48","occurrences":1}]}]},{"type":"segment","tag":"QTY","elements":[{"type":"composite","elements":[{"type":"data","value":"21","occurrences":1},{"type":"data","value":"288","occurrences":1}]}]},{"type":"segment","tag":"QTY","elements":[{"type":"composite","elements":[{"type":"data","value":"59","occurrences":1},{"type":"data","value":"12","occurrences":1}]}]},{"type":"segment","tag":"PRI","elements":[{"type":"composite","elements":[{"type":"data","value":"AAA","occurrences":1},{"type":"data","value":"12.80","occurrences":1},{"type":"data","value":"CT","occurrences":1},{"type":"data","value":"AAE","occurrences":1}]}]},{"type":"segment","tag":"SCC","elements":[{"type":"data","value":"7","occurrences":1}]},{"type":"segment","tag":"UNS","elements":[{"type":"data","value":"S","occurrences":1}]},{"type":"segment","tag":"UNT","elements":[{"type":"data","value":"21","occurrences":1},{"type":"data","value":"1","occurrences":1}]}]},{"type":"segment","tag":"UNE","elements":[{"type":"data","value":"1","occurrences":1},{"type":"data","value":"1","occurrences":1}]}]},{"type":"segment","tag":"UNZ","elements":[{"type":"data","value":"1","occurrences":1},{"type":"data","value":"2722166169492","occurrences":1}]}]}
Actual   :{"type":"interchange","header":{"type":"header","version":["UNOA","3"],"standard":"EDIFACT","delimiters":{"io.xlate.edi.stream.delim.segment":"'","io.xlate.edi.stream.delim.dataElement":"+","io.xlate.edi.stream.delim.release":"?","io.xlate.edi.stream.delim.decimal":".","io.xlate.edi.stream.delim.componentElement":":"}},"elements":[{"type":"segment","tag":"UNA","elements":[{"type":"data","value":" ","occurrences":1}]},{"type":"segment","tag":"UNB","elements":[{"type":"composite","elements":[{"type":"data","value":"UNOA","occurrences":1},{"type":"data","value":"3","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"5400110000009","occurrences":1},{"type":"data","value":"14","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"5013546107732","occurrences":1},{"type":"data","value":"14","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"010502","occurrences":1},{"type":"data","value":"1237","occurrences":1}]},{"type":"data","value":"2722166169492","occurrences":1},{"type":"composite","elements":[]},{"type":"data","value":"","occurrences":1},{"type":"data","value":"I","occurrences":1},{"type":"data","value":"0","occurrences":1},{"type":"data","value":"EANCOM","occurrences":1},{"type":"data","value":"1","occurrences":1}]},{"type":"group","name":"GROUP","elements":[{"type":"segment","tag":"UNG","elements":[{"type":"data","value":"ORDERS","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"5400110000009","occurrences":1},{"type":"data","value":"14","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"5013546107732","occurrences":1},{"type":"data","value":"14","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"010502","occurrences":1},{"type":"data","value":"1237","occurrences":1}]},{"type":"data","value":"1","occurrences":1},{"type":"data","value":"UN","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"D","occurrences":1},{"type":"data","value":"96A","occurrences":1},{"type":"data","value":"EAN008A","occurrences":1},{"type":"data","value":"IGNORED","occurrences":1}]}]},{"type":"transaction","elements":[{"type":"segment","tag":"UNH","elements":[{"type":"data","value":"1","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"ORDERS","occurrences":1},{"type":"data","value":"D","occurrences":1},{"type":"data","value":"96B","occurrences":1},{"type":"data","value":"UN","occurrences":1},{"type":"data","value":"EAN008B","occurrences":1}]}]},{"type":"segment","tag":"BGM","elements":[{"type":"data","value":"220","occurrences":1},{"type":"data","value":"C1441747","occurrences":1}]},{"type":"segment","tag":"DTM","elements":[{"type":"composite","elements":[{"type":"data","value":"137","occurrences":1},{"type":"data","value":"200105022200","occurrences":1},{"type":"data","value":"203","occurrences":1}]}]},{"type":"segment","tag":"FTX","elements":[{"type":"data","value":"PUR","occurrences":1},{"type":"data","value":"1","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"THIS IS AN EXAMPLE OF EDIFACT FILE.","occurrences":1}]},{"type":"segment","tag":"NAD","elements":[{"type":"data","value":"BY","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"5400110000009","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"9","occurrences":1}]}]},{"type":"segment","tag":"NAD","elements":[{"type":"data","value":"SU","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"5013546107732","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"9","occurrences":1}]},{"type":"data","value":"COMPANY ABC","occurrences":1}]},{"type":"segment","tag":"LIN","elements":[{"type":"data","value":"1","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"5400111864181","occurrences":1},{"type":"data","value":"EN","occurrences":1}]}]},{"type":"segment","tag":"PIA","elements":[{"type":"data","value":"1","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"8641800","occurrences":1},{"type":"data","value":"BP","occurrences":1}]}]},{"type":"segment","tag":"IMD","elements":[{"type":"data","value":"C","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"CU","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"9","occurrences":1},{"type":"data","value":"WIDGETS","occurrences":1}]}]},{"type":"segment","tag":"IMD","elements":[{"type":"data","value":"F","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"","occurrences":1},{"type":"data","value":"0.7066 EURO","occurrences":1}]}]},{"type":"segment","tag":"MEA","elements":[{"type":"data","value":"PD","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"LAY","occurrences":1},{"type":"data","value":"4","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"NAR","occurrences":1},{"type":"data","value":"6","occurrences":1}]}]},{"type":"segment","tag":"MEA","elements":[{"type":"data","value":"PD","occurrences":1},{"type":"composite","elements":[{"type":"data","value":"ULY","occurrences":1},{"type":"data","value":"4","occurrences":1}]},{"type":"composite","elements":[{"type":"data","value":"NAR","occurrences":1},{"type":"data","value":"48","occurrences":1}]}]},{"type":"segment","tag":"QTY","elements":[{"type":"composite","elements":[{"type":"data","value":"21","occurrences":1},{"type":"data","value":"288","occurrences":1}]}]},{"type":"segment","tag":"QTY","elements":[{"type":"composite","elements":[{"type":"data","value":"59","occurrences":1},{"type":"data","value":"12","occurrences":1}]}]},{"type":"segment","tag":"PRI","elements":[{"type":"composite","elements":[{"type":"data","value":"AAA","occurrences":1},{"type":"data","value":"12.80","occurrences":1},{"type":"data","value":"CT","occurrences":1},{"type":"data","value":"AAE","occurrences":1}]}]},{"type":"segment","tag":"SCC","elements":[{"type":"data","value":"7","occurrences":1}]},{"type":"segment","tag":"UNS","elements":[{"type":"data","value":"S","occurrences":1}]},{"type":"segment","tag":"UNT","elements":[{"type":"data","value":"21","occurrences":1},{"type":"data","value":"1","occurrences":1}]}]},{"type":"segment","tag":"UNE","elements":[{"type":"data","value":"1","occurrences":1},{"type":"data","value":"1","occurrences":1}]}]},{"type":"segment","tag":"UNZ","elements":[{"type":"data","value":"1","occurrences":1},{"type":"data","value":"2722166169492","occurrences":1}]}]}

```

I use Jackson inheritance so the type is mandatory

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
    @Type(value = Interchange.class, name = "interchange"),
    @Type(value = Loop.class, name = "loop"),
    @Type(value = Group.class, name = "group"),
    @Type(value = Composite.class, name = "composite"),
    @Type(value = Transaction.class, name = "transaction"),
    @Type(value = Segment.class, name = "segment"),
    @Type(value = Data.class, name = "data"),
    @Type(value = Header.class, name = "header"),
})
public abstract class Node implements Element {

}
```

this way the object mapper can marshal and unmarshal it 

the Header is not strictly an EDI element, it just help me with setting the factory parameters before writing to EDI

```
    EDIOutputFactory factory = EDIOutputFactory.newFactory();
    root.getHeader().getDelimiters().forEach(factory::setProperty);
```

will you take contributions?
Happy to make an initial stab at it :)

**Comment by MikeEdgar** [comment]
@gadieichhorn - I absolutely will take contributions. Like I mentioned, this can ideally be done with standard Java interfaces (or perhaps an interface defined by a well-known JSR like JSR-353). If you are willing to do a PR, perhaps we can work through the implementation there? I think the JSON format you're proposing is pretty close to what I was thinking, but we may need to negotiate to reach a final structure. For example, it would be ideal to have the values of the `type`s align with the namespaces used for XML, given in `EDINamespaces` - not the full names, but the final part of the URN in singular.

How is the `occurrences` property used?

I think the differences you are seeing between the 'actual' and 'expected' results is that the `UNA` segment is generated due to the delimiters being specified on the `EDIOutputFactory`. The writer is not currently "smart enough" to know if the user has given the default delimiters and suppress the `UNA` from being written.

**Comment by gadieichhorn** [comment]
great! I will ask permission before I can share commercial code here.

Yes, naming is never an issue for me :) what about [transaction, group, data, error, interchange]?

occurrences are something I saw you use in one of your examples and I thought this is important for the marshaling.  it can easily be replaced by the actual element count for each node.

I don't write the header to the output stream, Should I add it in? 
Maybe it is because I don't write the version/standards?

I was thinking maybe the delimiters should be on another abstraction, "envelop", that will wrap the interchange and will not be marshaled at all.

**Comment by MikeEdgar** [comment]
I am thinking that each "level" use the same key names: `"name"`, `"type"` (**required**), `"meta"`, and `"value"` (**required**). Types would align with the XML name spaces from `EDINamespaces` - `"loop"`, `"segment"`, `"composite"`, and `"element"`. Think of the envelops as special cases of loops. The name only needs to be present for loops and segments. Optionally, information from the schema could be put into `"meta"`, but we don't need to be worried about that for now. 

I applied this to your example and came up with the example below (with just the interchange and UNB to be brief). What are your thoughts about implementing a `javax.json.stream.JsonParser` (from JSR-353 and 374) that emits JSON events to match this, based on an underlying `EDIStreamReader`? It would be similar to how `StaEDIXMLStreamReader` implements `javax.xml.stream.XMLStreamReader` and makes the input look like a standard XML stream. Does your case require both the reader and writer, or only one of them for now?

```json
{
  "name": "INTERCHANGE",
  "type": "loop",
  "meta": {
    "standard": "EDIFACT",
    "version": [
      "UNOA",
      "3"
    ],
    "delimiters": {
      "io.xlate.edi.stream.delim.segment": "'",
      "io.xlate.edi.stream.delim.dataElement": "+",
      "io.xlate.edi.stream.delim.release": "?",
      "io.xlate.edi.stream.delim.decimal": ".",
      "io.xlate.edi.stream.delim.componentElement": ":"
    }
  },
  "value": [
    {
      "name": "UNB",
      "type": "segment",
      "value": [
        {
          "type": "composite",
          "value": [
            {
              "type": "element",
              "value": "UNOA"
            },
            {
              "type": "element",
              "value": "3"
            }
          ]
        },
        {
          "type": "composite",
          "value": [
            {
              "type": "element",
              "value": "5400110000009"
            },
            {
              "type": "element",
              "value": "14"
            }
          ]
        },
        {
          "type": "composite",
          "value": [
            {
              "type": "element",
              "value": "5013546107732"
            },
            {
              "type": "element",
              "value": "14"
            }
          ]
        },
        {
          "type": "composite",
          "value": [
            {
              "type": "element",
              "value": "010502"
            },
            {
              "type": "element",
              "value": "1237"
            }
          ]
        },
        {
          "type": "element",
          "value": "2722166169492"
        },
        {
          "type": "composite",
          "value": []
        },
        {
          "type": "element",
          "value": ""
        },
        {
          "type": "element",
          "value": "I"
        },
        {
          "type": "element",
          "value": "0"
        },
        {
          "type": "element",
          "value": "EANCOM"
        },
        {
          "type": "element",
          "value": "1"
        }
      ]
    }
  ]
}
```

**Comment by gadieichhorn** [comment]
thank you, yeah, that will remove the need to enforce inheritance on the model, I like it. I am so used to Jackson that I didn't think about this option, I will give this a try. The marshaling will be interesting, see if I get the same JSON or same POJO.

I normally run a round trip test:
JSON -> POJO -> JSON
POJO -> JSON -> POJO

value might be confusing for both types, I will prefer the array to be named **elements** as it is not a simple value but an object.

Will this support the binary data?

How do you handle the Error events I mentioned above?

Yes, just one direction as we continue processing either as Pojo or as JSON downstream. 
Same for the way out. originating from another source potentially needs to represented as JSON and wired as EDI.

**Comment by gadieichhorn** [comment]
I forgot to add 
JSON -> EDI -> JSON
EDI -> JSON -> EDI
tests

**Comment by MikeEdgar** [comment]
@gadieichhorn , your comment about Jackson makes me wonder if the implementation of JSON would be best done in a separate addon module. That way we can have both Jackson and JSR-353 interfaces and users can choose the one that suites their needs. What do you think?

**Comment by gadieichhorn** [comment]
right, so you want to go straight from JSON to EDI without a POJO as a middle step?

**Comment by MikeEdgar** [comment]
I'm thinking the API should be unaware of the final destination of the json stream, and the source of JSON when writing. So, if we are reading EDI as JSON, the client can choose to bind to POJOs or stream the data some other way. That way support for large inputs won't require large amounts of memory, etc. Streaming events is the key idea, I would say.

**Comment by MikeEdgar** [comment]
@gadieichhorn , one other question. Is your end goal to have a JSON file or to bind EDI to POJOs?

**Comment by gadieichhorn** [comment]
The end goal is JSON -> EDI and EDI -> JSON.

We should be able to do both JSON and POJO in the generic design, right?

**Comment by MikeEdgar** [comment]
Yes, that's right. The caller will be able to bind the JSON to the POJO or just serialize to a file.

**Comment by MikeEdgar** [comment]
@gadieichhorn - I realized there were some unanswered questions from earlier.

1. Reporting of errors - I'm thinking it would be better to keep errors out of the JSON data itself and utilize the existing `EDIInputErrorReporter` capability. 
2. Binary data - this may be optional in the initial implementation, but this should be represented as a base-64 encoded string. This is how `StaEDIXMLStreamReader` handles it.
3. Revisiting the naming conventions, how about the following. This will give a consistent model throughout the JSON structure.
-- `"name"`(optional)
-- `"type"` (**required**)
-- `"meta"` (optional)
-- `"data"` (optional - always present except for missing simple element values)

I am strongly considering starting up a new repo specific to JSON functionality and moving the discussion over there. There is some benefit to have both a JSR-353 interface and a Jackson interface and it's a bit cleaner to make that an add-on set of modules. Any objection?

**Comment by gadieichhorn** [comment]
ok, thank you for the answers.

yes, a new model is fine for keeping it optional for users (in the same repo if you can).

I would prefer a model were data is data ("value") and elements are nested nodes of any object.

**Comment by MikeEdgar** [comment]
The reason I hesitate to use "elements" is that the term already has a different meaning in the context of EDI. This seems like something that perhaps could be configurable - there are likely many different preferences on this.

**Comment by gadieichhorn** [comment]
Does it not represent the same thing?
Remind me what is  **meta**?

**Comment by MikeEdgar** [comment]
Elements are the contents of a segment. It's possible that representing the contents of a loop as elements may be confusing for some.

`meta` could be the information such as version and delimiters on the interchange. It could also be used elsewhere to enable output of information from the schema such as an element's `title`, `description`, etc. Basically information that is useful but not what you would consider the data itself.

This discussion has definitely helped me get an understanding of how this can work - thanks for opening. Are you looking at an implementation from a Jackson perspective or JSR-353 (or neither)?

**Comment by gadieichhorn** [comment]
yes, make sense.

I am using camel [DataFormat](https://camel.apache.org/manual/latest/data-format.html) so a POJO will be best for this to work and this is also the standard for this kind of transformation. 

No problem, I wish I could contribute, I am still waiting for approvals...

**Comment by MikeEdgar** [comment]
I started taking a more serious look at an implementation for this. You mentioned that you're using DataFormat, so I assume you will be also writing your own implementation in your Camel route on top of the API provided here, correct?

The basic approach here will be to provide implementations of the following APIs to allow reading EDI as if JSON were being read:
* `jakarta.json.stream.JsonParser`
* `javax.json.stream.JsonParser`
* `com.fasterxml.jackson.core.JsonParser`

The user decides which API they want to use at run time, but all three essentially just proxy the EDI stream events as JSON stream events.

**Comment by gadieichhorn** [comment]
Yes, the camel is just how I intend to pipe this through the system, usually, this is used for POJO to stream and back.
It is normally done in a series of steps until you have the type you need.

I am not clear why we need 3 API support, maybe some examples will help here. did you start a branch for this?

**Comment by MikeEdgar** [comment]
The three APIs are there to be supportive of the environment users are running in. That is, users in Spring are generally using Jackson and Java EE environments use the JSR 353 API. They are similar enough that it is just plumbing to support both (or so it appears). My goal is to minimize forcing an additional JSON parser on users to bundle with their applications when their platform already has one.

I have a branch locally, but it's not pushed yet. When I get back to it I'll push to github. 

Were you able to get cleared for contributions?

**Comment by gadieichhorn** [comment]
right, but the end results are the same POJO objects?

Not yet, I am also in the process of changing jobs which makes this unclear :( 
The work I have done doesn't look like what you are planning so it doesn't matter, we can start fresh.

**Comment by MikeEdgar** [comment]
@gadieichhorn - I think the parsing part of this is just about done in PR #133. I want to review a bit more to make sure I am comfortable with the testing. Just to reiterate, the idea is that this supports reading EDI data as if it were actually JSON. There are a couple of options to control how element data is generated. It can either be a basic JSON type (string or number) within a segment object, or it can be an object. Additionally, you can opt to have empty elements signalled as JSON NULL values. There are a couple of example JSON files in the PR if you have time to review and offer feedback.

For your requirements, would you prioritize reading via Jackson or the ability to write JSON data (in the same format generated by the new parser)? I'm thinking this issue can be closed with the PR and additional issues opened to itemize the individual new features (i.e., support for `JsonGenerator`s and support for Jackson). I envision a Jackson parser defined very similarly to how the Java EE/Jakarta parsers are defined. That will give the capability to "plug in" EDI-as-JSON streams into any library or interface that understands those parsers' interfaces.

**Comment by gadieichhorn** [comment]
@MikeEdgar, I agree, thank you for the new feature!

I had a quick look, the JSON output looks better than what I came up with (more condense).
