### ISSUE TITLE
not working with Ecliple

### ISSUE THREAD

**Issue by vitalygoji** [xlate/staedi#144]
Description	Resource	Path	Location	Type
The package javax.xml is accessible from more than one module: <unnamed>, java.xml	StaEDIXMLStreamWriter.java	/staedi/src/main/java/io/xlate/edi/internal/stream	line 9	Java Problem
Description	Resource	Path	Location	Type
XMLConstants cannot be resolved to a variable	StaEDIXMLStreamWriter.java	/staedi/src/main/java/io/xlate/edi/internal/stream	line 199	Java Problem
Description	Resource	Path	Location	Type
XMLConstants cannot be resolved to a variable	StaEDIXMLStreamWriter.java	/staedi/src/main/java/io/xlate/edi/internal/stream	line 407	Java Problem

**Comment by MikeEdgar** [comment]
Hi @vitalygoji , are you using Eclipse version 2020-09? I had this same problem myself when the project builds using the Eclipse built-in JDK 14. Do you have another version of the JDK available that you can configure in Eclipse?

**Comment by MikeEdgar** [comment]
Hi @vitalygoji - were you able to resolve this with the suggestion in my earlier comment? I believe this is an issue with Eclipse and not this library.

**Comment by MikeEdgar** [comment]
Closing this as an Eclipse issue - please reopen if you disagree or the mentioned solution does not work for you.
