### ISSUE TITLE
Supported EDI Standards

### ISSUE THREAD

**Issue by quadcorps** [xlate/staedi#153]
Hi
According to your docs this library only supports X12 and EDIFACT. Are there any plans to add additional support for other standards like TRADACOMS for example?
Thanks

**Comment by MikeEdgar** [comment]
Hi @quadcorps - there have not been any requests for additional standards such as TRADACOMS, but I am not opposed to adding them. Are there others or just that?

If you have any documentation for TRADACOMS or specific message types you are using, that would be helpful to get things started.
