### ISSUE TITLE
Option to disable validation of code values in a control schema

### ISSUE THREAD

**Issue by MikeEdgar** [xlate/staedi#16]
Provide an option to disable validation of the value enumerations defined in a control schema. The option/property will be a `boolean` and can be set on an `EDIInputFactory` instance using the constant `EDIInputFactory.EDI_VALIDATE_CONTROL_CODE_VALUES`. The default value should be `true`.

This option/property will allow a user to utilize control schema validation for structural and data type constraints, but still provide support for custom values that may not be defined in the list of enumerated values for an element in the control schema.

**Comment by benisantos** [comment]
Thank you for this too :)

**Comment by MikeEdgar** [comment]
@benisantos , you're welcome. Let me know if you have any questions on how to use it before I get to updating the wiki. New version is 1.4.1
