### ISSUE TITLE
Invalid output when writing question mark(s) in writeElement() or writeComponent()

### ISSUE THREAD

**Issue by ronaldjmaas** [xlate/staedi#164]
**Describe the bug**
When I pass one or more questions marks as argument to writeElement() or writeComponent(), the output is incorrect. Questions marks are not properly escaped with the release character and subsequent parsing of the output will fail.

**To Reproduce**
Running the following JUnit test case results in an incorrect formatted output file "bad.edi". E.g.

UNB+UNO1:1++++'ISA+???'

	@Test
	public void writeCursesResponse2() throws IOException, EDIStreamException {
		final EDIOutputFactory factory = EDIOutputFactory.newFactory();
		//factory.setProperty(Delimiters.DECIMAL, ".");
		EDIStreamWriter writer = null;
		try (final OutputStream out = new FileOutputStream("target/bad.edi")) {
			try {
				writer = factory.createEDIStreamWriter(out);
				writer.startInterchange();
				writer.writeStartSegment("UNB").writeStartElement().writeComponent("UNO1").writeComponent("1").endElement().
					writeEmptyElement().writeEmptyElement().writeEmptyElement().writeEmptyElement().writeEndSegment();
				writer.writeStartSegment("ISA").writeElement("???").writeEndSegment();
				writer.endInterchange();
			} finally {
				if (writer != null) {
					writer.close();
				}
			}
		}
	}

**Expected behavior**

An output file with the following content:

UNB+UNO1:1++++'ISA+??????'

**Additional context**

I think the following code change in io.xlate.edi.internal.stream.tokenization.CharacterClass should fix the issue but had no time to verify if this is the case:

    public boolean isDelimiter(int character) {
        switch (getClass(character)) {
        case ELEMENT_DELIMITER:
        case ELEMENT_REPEATER:
        case SEGMENT_DELIMITER:
        case COMPONENT_DELIMITER:
        case RELEASE_CHARACTER:
            return true;
        default:
            return false;
        }
    }

Thank you in advance.
Ronald Maas

**Comment by MikeEdgar** [comment]
@ronaldjmaas - thanks again for the suggestion and test case. This is in release 1.16.1 which should be available in Maven Central shortly.
