### ISSUE TITLE
Extend EDIStreamWriter from Closeable interface

### ISSUE THREAD

**Issue by ronaldjmaas** [xlate/staedi#165]
**Is your feature request related to a problem? Please describe.**
This code fragment won't compile because EDIStreamWriter does not implement the Closeable interface:

try (final OutputStream out = new FileOutputStream("example.edi");
final EDIStreamWriterwriter = factory.createEDIStreamWriter(out)) {
}

**Describe the solution you'd like**
Propose to change the interface definition of EDIStreamWriter to:

public interface EDIStreamWriter extends Closeable {
}

**Describe alternatives you've considered**

**Additional context**

Thanks in advance,
Ronald Maas

**Comment by MikeEdgar** [comment]
This will be done for the next release. Note that `AutoCloseable` will be used instead of `Closeable` due to the type of exception thrown by the `EDIStreamWriter`.
