### ISSUE TITLE
Ability to ignore malformed characters in the Lexer

### ISSUE THREAD

**Issue by hoffrocket** [xlate/staedi#201]
**Is your feature request related to a problem? Please describe.**
I sometimes encounter edi files with malformed UTF-8 input. 
Specifically, we see a 0x96 character in a string value which represents an En dash in ISO-8859-1

**Describe the solution you'd like**
Java already has a built-in mechanism to ignore malformed characters in `CharsetDecoder`, but we don't have the ability to set that option in the staedi API: `decoder.onMalformedInput(CodingErrorAction.IGNORE);`

**Describe alternatives you've considered**
Alternatively I could rewrite the input bytes before passing them into staedi, but that would be pretty expensive.

**Additional context**
Add any other context or code examples about the feature request here.

This test in `LexerTest.java` seems to reproduce the issue:
``` java
    @Test
    void testInvalidCharsetCharacter() throws Exception {
        byte [] bytes = (""
        + "ISA*00*          *00*          *ZZ*ReceiverID     *ZZ*Sender         *050812*1953*^*00501*508121953*0*P*:~"
        + "TA*foo   bar").getBytes();
        bytes[bytes.length - 5] = (byte)0x96;
        InputStream stream = new ByteArrayInputStream(bytes);
        TestLexerEventHandler eventHandler = new TestLexerEventHandler();
        final StaEDIStreamLocation location = new StaEDIStreamLocation();
        final Lexer lexer = new Lexer(stream, StandardCharsets.UTF_8, eventHandler, location, true);
        for (int i = 0; i < 22; i++) {
            lexer.parse(); // Interchange start through end of ISA
        }
    }
```

**Comment by MikeEdgar** [comment]
Is the input actually using encoding Windows-1252? I'm curious if creating a reader with that encoding would work. Of course that adds some additional complexity to the application.

**Comment by hoffrocket** [comment]
Possibly, I'm trying to determine if all the files can be reliably parsed in cp1252 which would certainly simplify

**Comment by hoffrocket** [comment]
Going to close this out as it seems that I can reliably parse all files as cp1252.
