### ISSUE TITLE
How to obtain transaction version information?

### ISSUE THREAD

**Issue by vkjandhya** [xlate/staedi#210]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or code examples about the feature request here.

**Comment by vkjandhya** [comment]
Here is an issue/ feature
Let's say there are incoming edi messages coming either in 4010/5010/6010 version format!  Is there anyway to determine message version prior to  so as to validate/process each message using appropriate schema?
thanks

**Comment by MikeEdgar** [comment]
@vkjandhya - please see the method `EDIStreamReader#getTransactionVersion`. If you are dealing with X12, you can retrieve the version information when you receive the `END_SEGMENT` event for the `ST` segment.

**Comment by MikeEdgar** [comment]
@vkjandhya - were you able to get things working?

**Comment by vkjandhya** [comment]
Hi Mike,
Yes, of course!
Thanks
