### ISSUE TITLE
Add support for partial validation

### ISSUE THREAD

**Issue by benisantos** [xlate/staedi#23]
It would be appreciated if the transaction schema could support something like "wildcard sequences" inside a `segmentType` declaration.

The idea is to skip validation of elements/composites of some segments. This can be useful when you are dealing with big "models", and you are only interested in parse and validate part of the "model". 

The syntax could be something like:

```xml
<segmentType name="FOO">
    <sequence>
    	<any/>
    </sequence>
</segmentType>
```
It's similar to the "any" element in XSD (with processContents="skip"): https://www.w3schools.com/xml/el_any.asp

Thanks in advance

**Comment by MikeEdgar** [comment]
@benisantos, thanks for opening this issue. I am considering if there are any negative side affects from supporting something like this.

Have you considered trying something like this?

```xml
<elementType name="AnyElement" base="string" maxLength="99999" />

<segmentType name="FOO">
    <sequence>
      <element ref="RealElement1" minOccurs="1" />
      <element ref="RealElement2" />
      <element ref="AnyElement" />
      <element ref="AnyElement" />
      <element ref="AnyElement" />
    </sequence>
  </segmentType>
```

**Comment by benisantos** [comment]
> Have you considered trying something like this?

Yes, I have. I don't like so much that workaround because I guess it has some impact on performance (comparing to do a real skip). 

At this moment, my workaround is to define my "any" segments like empty segments:
```xml
<segmentType name="FOO">
    <sequence/>
</segmentType>
```
and ignore `TOO_MANY_DATA_ELEMENTS` on that cases.

**Comment by MikeEdgar** [comment]
Performance shouldn't be impacted too much either way. Can I assume this request is mainly because you're dealing with specifications in PDF that need to be coded in the schema manually? Would you ideally have the full segment schema and just ignore the data when parsing?

**Comment by MikeEdgar** [comment]
@benisantos - additionally, do you have cases where the segment needs some elements validated and others not validated? Or is it all or nothing?

**Comment by benisantos** [comment]
> Can I assume this request is mainly because you're dealing with specifications in PDF that need to be coded in the schema manually? 

Yes, you can. Now, I only interested in parse (and validate) some segments. Later, it might be that I had to validate all of them. It's not sure.

> Would you ideally have the full segment schema and just ignore the data when parsing?

Yes, I would. But code a full schema is out of scope now :( I only need "full" validation in some segments. Moreover, I'm afraid that some clients don't fulfill the full specs.

> additionally, do you have cases where the segment needs some elements validated and others not validated? Or is it all or nothing?

At this moment, it's all or nothing. But, in the medium/long term, maybe the other way.

**Comment by MikeEdgar** [comment]
@benisantos - please take a look at version `1.6.0` when you get a chance, along with the [updated documentation](https://github.com/xlate/staedi/wiki/Validation#lax-validation-since-160).

Please let me know if you hit any bugs with the new feature. Thanks!

**Comment by benisantos** [comment]
Thank you @MikeEdgar !
My first tests have been successful :)
