### ISSUE TITLE
Is the built in control Schema supposed to validate GE and IEA and SE counters?

### ISSUE THREAD

**Issue by jfrense** [xlate/staedi#254]
I was under the impression that setting the following property (default):

```         
factory.setProperty(EDIInputFactory.EDI_VALIDATE_CONTROL_CODE_VALUES, true);
```

would result in validating the counters in the following control trailers (SE, GE, IEA). 

However when I intentionally test EDI documents with incorrect counters, it still passes the validation stage. Is this intentional? Are we expected to validate the counts manually?

Ex:
```
ISA*00*          *00*          *ZZ*TSTCOMPANY*ZZ*TSTCOMPANY  *220213*0034*|*00501*100000024*0*P*}
GS*PO*TSTCOMPANY*TSTCOMPANY*20220213*0034*1024*X*005010
ST*850*1024
BEG*00*DS*123123**20220213
REF*IA*2820675
REF*CO*CO1234
N9*L1*GEN
MTX**Order notes to be sent here
N1*ST*John Doe
N3*123 Main St
N4*Minneapolis**55111
PO1*001*1*EA*1180**VN*MFRN0982-PCD-OS
PID*F*08***Sofa
PO1*002*2*EA*650**VN*MFRN1544-FWN-OS
PID*F*08***Chair
PO1*003*1*EA*1250**VN*MFRN1881-OWH-Q
PID*F*08***Bed
PO1*004*4*EA*650**VN*MFRN1544-BLK-OS
PID*F*08***Chair
SE*18*1024
GE*1*1024
IEA*0*100000024
```
^^In IEA segment with Element of position 1 incorrectly set to 0 which is supposed to count the number of functional groups in the EDI message. Still passes validation.

**Comment by MikeEdgar** [comment]
Hi @jfrense - `EDI_VALIDATE_CONTROL_CODE_VALUES` only enables/disables the validation of the "code" fields. For example, whether GS01=PO is a valid value for that element. Validation of trailer counters and checking that header/trailer control numbers match is a feature that has not yet been implemented, but certainly would be useful.

**Comment by jfrense** [comment]
@MikeEdgar got it! thank for the quick response.
