### ISSUE TITLE
Validate control numbers and counters

### ISSUE THREAD

**Issue by MikeEdgar** [xlate/staedi#256]
For each control structure (interchange, group, transaction):
- validate that the control number in the header and trailer matches
- validate that the actual count (segment count for transactions, transaction count for groups, and group count for interchanges) matches the count included in the trailer segment

Relates to #254

**Comment by NandaBalakrishnan** [comment]
Any updates on this enhancement?

**Comment by MikeEdgar** [comment]
Hi @NandaBalakrishnan this will be in the next release. I'll likely have some time to get to it later this week or early next.

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan , @Rekha-Prakash  - this was implemented in #301 and now available in v1.21.0

**Comment by Rekha-Prakash** [comment]
@MikeEdgar , I tried the new release and the features are working fine for ISA and group,  but not for the transactions. 

I have added the changes in v00402.xml as well in my project,

```
<interchange header="ISA" trailer="IEA" title="X12 Interchange (minimum version 00402)" headerRefPosition="13" trailerRefPosition="2" trailerCountPosition="1" countType="controls">
        <sequence>
            <group header="GS" trailer="GE" headerRefPosition="6" trailerRefPosition="2" trailerCountPosition="1" countType="controls">
                <transaction header="ST" trailer="SE" headerRefPosition="2" trailerRefPosition="2" trailerCountPosition="1" countType="segments"/>
            </group>
```
can you please check if I am missing anything else ?

**Comment by MikeEdgar** [comment]
@Rekha-Prakash , your schema is correct. I'll check and see if something has been missed. Are both types of validation not working? Control number and segment count?

**Comment by Rekha-Prakash** [comment]
@MikeEdgar Yeah, both validation not working for the transactions.

**Comment by Rekha-Prakash** [comment]
Hi @MikeEdgar , just checking in if you had a chance to check on this ?

**Comment by MikeEdgar** [comment]
@Rekha-Prakash , unfortunately not yet. Hopefully in the next day or two. Did you try using the built-in control schemas? I'm curious if it's any different for you without a custom control schema.
