### ISSUE TITLE
write X12 file

### ISSUE THREAD

**Issue by cy798919835** [xlate/staedi#300]
Can I output X12 file without displaying segment terminator "~"? 
For example:
ISA*00*0000000000*00*0000000000*ZZ*528781144 *12*85224026644 *220524*1728*U*00401*000007936*0*T*>

**Comment by MikeEdgar** [comment]
Hello @cy798919835 - this should be possible by using `\n` as the segment terminator. See the wiki page on writing EDI [1] for example configurations.

[1] https://github.com/xlate/staedi/wiki/Writing-EDI-Data-(Configuration)

**Comment by cy798919835** [comment]
@MikeEdgar 
Thank you very much for solving my problem

**Comment by MikeEdgar** [comment]
Thanks @cy798919835 . I'll close this issue for now, but please re-open if you still are having any concerns.
