### ISSUE TITLE
Control reference and count validation inactive for X12

### ISSUE THREAD

**Issue by MikeEdgar** [xlate/staedi#311]
See https://github.com/xlate/staedi/issues/256#issuecomment-1290200961

**Comment by MikeEdgar** [comment]
@Rekha-Prakash - the fix is included in release v1.22.0. Please let me know if it does not work for you.

**Comment by Rekha-Prakash** [comment]
Thank you @MikeEdgar for fixing this bug , I will test it and update you on this.

**Comment by Rekha-Prakash** [comment]
@MikeEdgar this is working as expected. Thanks much!
