### ISSUE TITLE
Read X12 File Error

### ISSUE THREAD

**Issue by cy798919835** [xlate/staedi#315]
Hello, when I read without the segment separator "~", the program could not find where SEGMENT ended. The program will treat all the information as a segment. The following is my program to read files:

final EDIInputFactory factory = EDIInputFactory.newFactory();
        factory.setProperty(EDIInputFactory.EDI_VALIDATE_CONTROL_CODE_VALUES, false);
        InputStream stream = new FileInputStream(new File(path));
        EDIStreamReader reader = factory.createEDIStreamReader(stream);

        List<SaEdi> saEdiList = new ArrayList<>();
        SaEdi saEdi = null;
        Map<String,String> map = null;
        int index = 0;
        String segmentName="";
        while (reader.hasNext()) {
            switch (reader.next()) {
                case START_INTERCHANGE:
                    System.out.println(reader);
                    break;

                case START_SEGMENT:
                    System.out.println(reader);
                    break;

                case END_SEGMENT:
                    System.out.println(reader);
                    break;

                case START_COMPOSITE:
                    System.out.println(reader);
                    break;

                case END_COMPOSITE:
                    System.out.println(reader);
                    break;

                case ELEMENT_DATA:
                    System.out.println(reader);
                    break;
            }
        }
        reader.close();
        stream.close();

**Comment by MikeEdgar** [comment]
Hi @cy798919835 , do you have a sample of the EDI data to share? What is the segment separator in your file?

**Comment by cy798919835** [comment]
Hi @MikeEdgar ，The following is my EDI file. ISA, GS, ST, and BSN are all segment separators: "~", and HL, N1, and LIN have no segment separators: "~". When the program finishes reading the BSN, it doesn't know where it ends.

ISA*00*          *00*          *12*85224026644    *01*528781144      *221122*1630*U*00401*000043563*0*T*:~
GS*SH*85224026644*528781144*20221122*1630*10571*X*004010~
ST*856*10571~
BSN*00*24360008930~
HL*1**S
N1*ABG**ZZ*2436
HL*2*1*O
LIN**VN*019600958
SN1**70*PC
REF*LT*0
REF*L1*Remark1*22BUN411WLMQ1221122153806154
REF*ZZ**M18 FDG-401X-18C
N1*LSD*Mis-Rec
N1*ST*3PL-TRAD
N1*AO*MKE Bundle
SE*3*10571~
GE*1*10571~
IEA*1*000043563~

**Comment by cy798919835** [comment]
@MikeEdgar Yes, some segments do not have segment separators, so I cannot parse them correctly. Do you have any good suggestions

**Comment by MikeEdgar** [comment]
I would suggest starting by contacting the company/individual that is generating the files without segment separators. If that doesn't work, you may be able to pre-process the data using something like `sed` (assuming you're in a Linux/Unix/MacOS environment).

**Comment by cy798919835** [comment]
@MikeEdgar Thank you very much. I'll try to preprocess the file
