### ISSUE TITLE
Support to Split mulitple GS into separate EDI files

### ISSUE THREAD

**Issue by NandaBalakrishnan** [xlate/staedi#318]
required simple and efficient way to split multiple GS into separate edi files

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan - you will probably need a more advanced filter, like below. Basically, you'll need to keep track of which transaction is currently being read and filter accordingly.

```java
EDIStreamReader reader = factory.createEDIStreamReader(stream);
reader = factory.createFilteredReader(reader, new EDIStreamFilter() {
    String transactionType = null;

    @Override
    public boolean accept(EDIStreamReader r) {
       
        switch (r.getEventType()) {
        case EDIStreamEvent.START_TRANSACTION:
        case EDIStreamEvent.END_TRANSACTION:
            transactionType = null;
            break;
        case EDIStreamEvent.END_SEGMENT:
            if ("ST".equals(r.getText())) {
                transactionType = r.getTransactionType();
            }
            break;

        }
        
        return "810".equals(transactionType) || transactionType == null;
    }
});
```

**Comment by NandaBalakrishnan** [comment]
@MikeEdgar , i am using this version of 
(https://github.com/xlate/staedi/blob/master/src/main/resources/X12/v00402.xml )
when i do  reader.getDelimiters(), getting only SEGMENT, DATA_ELEMENT, COMPONENT_ELEMENT and DECIMAL, want to understand why REPETITION delimeter is not available when streaming edi file?

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan , does the `ISA` segment have one specified and is the version >= 00402?

**Comment by NandaBalakrishnan** [comment]
Yes @MikeEdgar

**Comment by MikeEdgar** [comment]
If you have a sample EDI file with the issue I will take a look at it.

**Comment by NandaBalakrishnan** [comment]
Sure , 
ISA*00*          *00*          *02*SOFT           *01*006999942      *220708*1516*U*00400*00167837*0*P*>~GS*AF*SOFT*006097142*20220708*1516*00167837*X*004010~GE*1*00167837~IEA*1*0067837~

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan , the version in that segment is `00400`. The version must be at least `00402` for the repetition delimiter to work. Also, that segment _would_ use `U` as the repetition, which I think you would not want.

**Comment by NandaBalakrishnan** [comment]
@MikeEdgar is there a way to unwrap the input edi file based on segment terminator?

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan , please use [discussions](https://github.com/xlate/staedi/discussions) for general questions. I'll close this issue for now as support for splitting files is out of scope for the library. Something like that would be developed in an application or library layer above the EDI stream processing.
