### ISSUE TITLE
Repetition Elements are not being correctly identified

### ISSUE THREAD

**Issue by ffffionn** [xlate/staedi#321]
**Describe the bug**
I don't seem to be able to correctly identify when the EDIStreamReader is processing a repeated element. 

**To Reproduce**
Example EDI: 
`ISA*00*          *00*          *ZZ*U1             *ZZ*DDPA           *221218*1001*^*00501*000243787*0*P*+~GS*HB*OR*DDPA*20221218*1001*243787*X*005010X279A1~ST*271*243787*005010X279A1~BHT*0022*11*1671386499287-0*20221218*1001~HL*1**20*1~NM1*PR*2*DELTA DENTAL OR*****PI*OR~HL*2*1*21*1~NM1*P5*1*UTMP*JOE****FI*000000000~HL*3*2*22*0~TRN*2*1671386499287-0*9DDPA-DDNP~NM1*IL*1*UTMP*JOE*M***MI*UTMP00001~REF*6P*0001*Test~N3*123 MAIN STREET*APT 12~N4*ANYTOWN*CA*90000~DMG*D8*19700101*M~INS*Y*18*001*25~EB*1*ESP*35**Preferred Provider Option~EB*A**23^41^ED^EE^EF^EG^EH^EI*****0****N~SE*17*243787~GE*1*243787~IEA*1*000243787~`

EDIStreamEvent on each alphanumeric of the `*23^41^ED^EE^EF^EG^EH^EI*` section of the final `EB` segment is read as ELEMENT_DATA and `((StaEDIStreamLocation) reader.location).isRepeated` gives `false` during that event where I would expect `true` on any of these.

**Expected Behaviour**
Aside from the `reader.location.isRepeated` issue above, I would also maybe expect EDIStreamEvent similar to `START_COMPOSITE`/`END_COMPOSITE`  -- like `START_REPEATED`/`END_REPEATED`

**Additional context**

I can see in my IDE debugger that the property `repeated` is set correctly as true, but reading that `location` object off of the reader is giving a different object reference.
I am using v1.20 of the library.

**Comment by ffffionn** [comment]
![image](https://user-images.githubusercontent.com/9085250/209348211-d06b9a94-0185-4f0b-b560-9bb43383f4e7.png)

**Comment by MikeEdgar** [comment]
@ffffionn the information you are looking for is in `Location.getElementOccurrence`. This will be a value from 1 to X and is incremented each time an element repeats. The reason you see different objects internal to the reader is that there are multiple instances to support the event queuing necessary for handling more complex structures in the EDI data.

Note that the `Location` returned from the reader is only accurate until `next` is called. If you need to keep a stable location, use `location.copy()`.

**Comment by ffffionn** [comment]
@MikeEdgar   perfect, that does exactly what I need it to - was just getting confused/misled by the `repeated` property
