### ISSUE TITLE
Error reported when reading ANSI encoded txt file

### ISSUE THREAD

**Issue by cy798919835** [xlate/staedi#323]
When a java program reads an ANSI encoded txt file, the following error will be reported when it reads the following paragraph:
java.nio.charset.MalformedInputException: Input length = 1

Contents read at the beginning of error reporting:
IMD+8++:: K2070414 INGENIO R 蹾 RSCH jump SEL:: DE '

**Comment by MikeEdgar** [comment]
@cy798919835 do you have any additional details or a small test case on this?

**Comment by MikeEdgar** [comment]
> is there a way we can generate ANSI through EDIStreamWriter?

@saravanan-periyasamy03 , have you tried using the `encoding` parameter when creating the `EDIStreamWriter` ?

```java
EDIOutputFactory factory = EDIOutputFactory.newFactory();
EDIStreamWriter writer = factory.createEDIStreamWriter(stream, "US-ASCII");
```

**Comment by saravanan-periyasamy03** [comment]
Hi @MikeEdgar ,
Tried the same code and I'm observing weird error were at the end of terminator one extra(dot) char is getting added. Even it is happening for default UTF-8 encoding.

In the below sample, ~ is the terminator we are getting from clients. Due to the extra dot at the end it's failing for clients.

**997 Sample generated:**
```
ISA*00*           *00*          *02*SAWR           *02*00765453      *230108*0220*U*00400*000123422*0*T*>~.
GS*FA*SAWR*00765453*20230108*0220*342234*X*004010~.
ST*997*0001~.
SE*2*0001~.
GE*1*342234~.
IEA*1*000123422~.
```

Even tried ISO-8589-1 encoding but still the same. Any help is highly appreciated.

**Comment by MikeEdgar** [comment]
The default for `line.separator` is platform-dependent [1]. Do the dots appear if pretty-print is disabled?

[1] https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#lineSeparator--

**Comment by saravanan-periyasamy03** [comment]
Hi @MikeEdgar ,

Few observations based on testing,

1. When we try to set `factory.setProperty(EDIOutputFactory.PRETTY_PRINT,false); ` to false then getting exception `Exception Occurred in writeAck route io.xlate.edi.stream.EDIStreamException: Invalid X12 ISA segment: too short or elements missing`
2. If `factory.setProperty(EDIOutputFactory.PRETTY_PRINT,true); ` to true and  line separator  set to `System.setProperty("line.separator","");` without space then getting same exception `Exception Occurred in writeAck route io.xlate.edi.stream.EDIStreamException: Invalid X12 ISA segment: too short or elements missing`
3. If `factory.setProperty(EDIOutputFactory.PRETTY_PRINT,true); ` to true and  line separator  set to `System.setProperty("line.separator"," ");`with single space then ACK is getting generated successfully but we see space after terminator instead of dot(.) now

Our system is running on linux.

**Comment by MikeEdgar** [comment]
@saravanan-periyasamy03 have you set delimiters or are you using the defaults for X12? If you're free to share the code that is writing the header, that might help.

**Comment by MikeEdgar** [comment]
I wonder if they are not matching? Try this instead:
```java
Map<String, String> senderDelimiters = reader.getDelimiters();
...
senderDelimiters.forEach(factory::setProperty);

```

**Comment by saravanan-periyasamy03** [comment]
Hi @MikeEdgar ,

We applied above option as well but still getting the same error (dot) is coming.

We tried different combination to fix this problem and one of the combination worked for now but wanted to check on the impact of the change we made on the EDIStreamWriter(writeEndSegment()).

Changes made are below,

1. **PRETTY_PRINT** and **line.separator** is not defined in writer
```
//    System.setProperty("line.separator","");
//    factory.setProperty(EDIOutputFactory.PRETTY_PRINT,true);
```
2. In package `io.xlate.edi.internal.stream`, in **writeEndSegment()** method, commented highlighted throw exception **`throw new EDIStreamException("Invalid X12 ISA segment: too short or elements missing");`.**

`    @Override
    public EDIStreamWriter writeEndSegment() throws EDIStreamException {
        ensureLevelAtLeast(LEVEL_SEGMENT);
        if (level > LEVEL_SEGMENT) {
            validateElement(this.elementBuffer::flip, this.elementBuffer);
        }
        validate(validator -> validator.validateSyntax(dialect, this, this, location, false));

        if (state == State.ELEMENT_DATA_BINARY) {
            state = State.ELEMENT_END_BINARY;
        }

        writeSegmentTerminator();

        switch (state) {
            case SEGMENT_END:
            case HEADER_SEGMENT_END:
            case INITIAL: // Ending final segment of the interchange
                break;
            default:
                if (state.isHeaderState() && dialect instanceof X12Dialect) {
                   // throw new EDIStreamException("Invalid X12 ISA segment: too short or elements missing");
                }
                break;
        }`

**Comment by MikeEdgar** [comment]
@saravanan-periyasamy03 it seems that this is a bug in the writer, but to be sure is there any way you could provide a small program that reproduces the error? I wouldn't recommend commenting the `throw`. Its purpose is to check that the state of the writer is not unexpected. Also, just to confirm, are you using the latest version?

**Comment by saravanan-periyasamy03** [comment]
Thanks @MikeEdgar . Let me give it a shot and keep you posted.

**Comment by saravanan-periyasamy03** [comment]
Hi @MikeEdgar ,

Tested with 1.22.1 version and configuration we had this time to make it work is,

- We didn't comment  `throw new EDIStreamException("Invalid X12 ISA segment: too short or elements missing")` in EDIStreamWriter in writeEndSegment() method.

- But still PRETTY_PRINT and line.separator is not defined in writer

```
//    System.setProperty("line.separator","");
//    factory.setProperty(EDIOutputFactory.PRETTY_PRINT,true);

```

Good part is we are not overriding **EDIStreamWriter** package.

But if we try to set PRETTY_PRINT to true , still the dot is getting added next to the terminator.

**Comment by MikeEdgar** [comment]
Thanks @saravanan-periyasamy03 . Can you grab the output of this just to confirm the line separator?
```java
System.out.printf("line.separator='");
for (byte b : System.getProperty("line.separator").getBytes()) {
    System.out.printf("%02x", b);
}
System.out.printf("'\n");
```

**Comment by saravanan-periyasamy03** [comment]
Hi @MikeEdgar ,

Executing above code results with below output,

line.separator='0a'
0a0a0a

**Comment by MikeEdgar** [comment]
@saravanan-periyasamy03 the output contains `0a0a0a` on a second line?

**Comment by saravanan-periyasamy03** [comment]
Yes @MikeEdgar . It's printed on second line

**Comment by MikeEdgar** [comment]
That seems strange... I really don't have any explanation for why the additional `0a` occurrences were printed. Are you running that locally or in your deployment environment?

**Comment by MikeEdgar** [comment]
Thanks @saravanan-periyasamy03 . The dots are not present in the output when pretty print is disabled, correct? Is there anything in your container image build process that sets or changes the encoding or line endings somehow? Also, would it be possible to put together a tiny reproducer program that exhibits the issue?

**Comment by MikeEdgar** [comment]
@cy798919835 , @saravanan-periyasamy03 - I'll leave this open for another week or so in case you can provide some additional detail or (ideally) a small project that demonstrates the issue in a repeatable way. Otherwise, it may be something specific to your environment.
