### ISSUE TITLE
Missing Mandatory Segments

### ISSUE THREAD

**Issue by NandaBalakrishnan** [xlate/staedi#340]
Missing mandatory segments

sample example

Actual EDI
```
ST*997*000033395
AK1*AB*980599
AK2*820*0001
AK5*E*4
AK9*E*1*1*1
SE*6*000033395
```

Missing AK1 segments
```
ST*997*000033395
AK2*820*0001
AK5*E*4
AK9*E*1*1*1
SE*6*000033395

```

i am getting segment error as below, 
SEGMENT_ERROR
(actualValue=AK1, elementId=AK1, elementPosition=-1, errorMessage=MANDATORY_SEGMENT_MISSING, errorType=SEGMENT_ERROR, lineNumber=1, segmentTag=AK2)

can you help me to understand why elementID, element Position and segment tag are wrong?
element id and position and segment tag should be referred from schema right

@MikeEdgar  pls help on this

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan , the location information given by the reader is usually based on the actual data. In this case, it's when the `AK2` segment is read that the the read is aware that the `AK1` is missing. 

Does that help?

**Comment by NandaBalakrishnan** [comment]
ya i created from reader and location only
  actualValue reader.getText()
  elementId  = reader.getReferenceCode()
elementPosition  = reader.getLocation().getElementPosition()
errorMessage  = reader.getErrorType()
ErrorType = ErrorType.SEGMENT_ERROR
SegmentTag = reader.getLocation().getSegmentTag()

**Comment by NandaBalakrishnan** [comment]
@MikeEdgar can you provide 997 example for missing mandatory segment of other doctype?

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan you would use an `AK3` segment for that. The first element would contain the tag of the missing segment and the second element would contain the numeric position where it is found to be missing.

**Comment by NandaBalakrishnan** [comment]
sure thank you.
