### ISSUE TITLE
How to apply relational condition in schema

### ISSUE THREAD

**Issue by NandaBalakrishnan** [xlate/staedi#347]
Hi @MikeEdgar  , want to know how this relational conditional can be applied to schema or is there any other way to achieve this? 

https://www.stedi.com/edi/essentials/x12/elements/relational-conditions

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan you can use the `syntax` element in the `segmentType`

For example:
https://github.com/xlate/staedi/blob/d16826093479ddb519b09618b445e4eba8c6f2be/src/test/resources/EDIFACT/CONTRL-v4r02.xml#L589-L592

The allowed values for `type` are defined here:

https://github.com/xlate/staedi/blob/d16826093479ddb519b09618b445e4eba8c6f2be/src/main/resources/schema/EDISchema-v4.xsd#L35-L73

**Comment by NandaBalakrishnan** [comment]
how to use it for x12 standard schema not for EDIFACT?

**Comment by MikeEdgar** [comment]
> how to use it for x12 standard schema not for EDIFACT?

It's the same for both

**Comment by NandaBalakrishnan** [comment]
ok sure @MikeEdgar , let me check sir. Thank you

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan  yes, it's listed along with the others: 

https://github.com/xlate/staedi/blob/master/src/main/java/io/xlate/edi/stream/EDIStreamValidationError.java#L23

**Comment by NandaBalakrishnan** [comment]
@MikeEdgar , since it is conditional relation, whether validation happens after the complete segment read ?

**Comment by MikeEdgar** [comment]
> since it is conditional relation, whether validation happens after the complete segment read ?

That's right, the relational conditions are not evaluated until the end of the segment.

**Comment by NandaBalakrishnan** [comment]
@MikeEdgar , how to get loop code in segment error case?

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan , one way is to keep track of it in your program. Save the value of `reader.getReferenceCode()` at the start of each loop.

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan , do you have any further questions on this topic? Please go ahead and close if not. Thanks!
