### ISSUE TITLE
X12 unexpected segment error occurred when first segment of loop is missing

### ISSUE THREAD

**Issue by NandaBalakrishnan** [xlate/staedi#357]
@MikeEdgar , child level loop segments are available properly but because of first segment of loop at root level is missing, it is throwing unexpected error for all segments and it is not generating json properly.

is there any attribute to find out whether segment is part of loop ?

**Comment by AnnapoorniS** [comment]
+1

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan, the first segment of a loop is critical to the structure of the EDI transaction. If your trading partner is sending you EDI with loop segments but missing the loop-start segment, the transaction is invalid and should be rejected/resent by your partner.

Consider the example below with indentation to show the structure. Without (for example) the `AK3` segment, if an `AK4` segment is received directly following an `AK2`, it is indeed an unexpected segment. No parser or consumer of the data should infer the `AK3` segment and its elements.

```edi
ISA*00*          *00*          *ZZ*ReceiverID     *ZZ*Sender         *050812*1953*^*00501*508121953*0*P*:~
  GS*FA*ReceiverDept*SenderDept*20050812*195335*000005*X*005010X230~
    ST*997*0001~
    AK1*HC*000001~
      AK2*837*0021~ // start of loop 2000
        AK3*NM1*8**8~ // start of loop 2100
        AK4*8*66*7*MI~
      AK5*R*5~
    AK9*R*1*1*0~
    SE*8*0001~
  GE*1*000005~
IEA*1*508121953~

```

**Comment by NandaBalakrishnan** [comment]
@MikeEdgar , Yes i understood how staedi works, but want to know is there any attribute to find out segment are at root level or it is with in some loop?

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan , you could navigate through the `Schema`. The standard schema is available via `getStandard`. All the relevant methods should be documented [1]. The schema tree is one-way, so you cannot navigate up to a parent from a node. Out of curiosity, what do you want to do with this information?

[1] https://javadoc.io/doc/io.xlate/staedi/latest/io.xlate.staedi/io/xlate/edi/schema/package-summary.html

**Comment by MikeEdgar** [comment]
Closing this for now, see comments in PR #365 for rationale.
