### ISSUE TITLE
Adding condition to writeSegment

### ISSUE THREAD

**Issue by saravanan-periyasamy03** [xlate/staedi#380]
Hi @MikeEdgar ,

We are trying to see if we can add conditional statements within the writeStartSegment to remove the null or empty values getting constructed in a segment.

We are printing the elements inside a segment dynamically using the data received.

Please see below writeStartSegment and output generated,

Ex 1:

```
writer.writeStartSegment("TA1")
              .writeElement("000000050")
              .writeElement("000000050")
              .writeElement("1200")
              .writeElement("A")
              .writeElement("000")
              .writeEndSegment();

TA1*000000050*000000050*1200*A*000~
```

Ex 2:

```
writer.writeStartSegment("TA1")
              .writeElement("000000050")
              .writeElement("000000050")
              .writeElement("1200")
              .writeElement("")
              .writeElement("")
              .writeEndSegment();

TA1*000000050*000000050*1200***~
```

In the above Ex 2 , last 2 elements are empty while writing the segment but we wanted to remove the empty elements with * and send output as below,

```
writer.writeStartSegment("TA1")
              .writeElement("000000050")
              .writeElement("000000050")
              .writeElement("1200")
              .writeElement("")
              .writeElement("")
              .writeEndSegment();

TA1*000000050*000000050*1200~
```

Is there a way to remove the elements which are not having values to it. If the initial elements are empty and last elements are having values then it is standard and we can have the empty elements.

But we wanted to remove the elements  which are empty and not having data for the following elements.

**Comment by MikeEdgar** [comment]
@saravanan-periyasamy03 , you can use the empty element truncation option to do this.

Please see https://github.com/xlate/staedi/wiki/Writing-EDI-Data-(Configuration)#truncate-empty-elements

**Comment by saravanan-periyasamy03** [comment]
Thank you @MikeEdgar for the details. We tested and works as expected.

**Comment by MikeEdgar** [comment]
Thanks for confirming :+1: . Closing issue.
