### ISSUE TITLE
Option to ignore repetition separator in the ST/SE segments

### ISSUE THREAD

**Issue by saravanan-periyasamy03** [xlate/staedi#383]
Hi @MikeEdgar ,

We are facing issues for few of the EDI files where consumers sending repetition(composite) separator in the ST/SE segments as below,

**ISA Segment:-**
`ISA*00*          *00*          *02*TYRD           *01*001021112      *230815*0600*U*00400*000283137*0*P*:~`

**ST/SE Segment:-**
`ST*214*43215111~
PRF*MILLWORK:LIT08-04-23~
SE*1*43215111~`

':" repetition separator is coming in the PRF segment, **EDIStreamReader** is throwing **not a valid text state [START_COMPOSITE]**

If the composite element definition is added in the EDI schema, then things will work without issues.

This is data issue from the consumer, but we are trying to see if there are any options to skip this validation or replace the repetition separator with space to complete the processing. I agree it is against the standard but until we fix the data problem we want to process the transactions.

**Comment by MikeEdgar** [comment]
Hi @saravanan-periyasamy03 , do you mean that the composite separator is used in the data and it should not be interpreted as such? Since the `ISA` version is `00400`, the repetition feature of X12 isn't actually enabled for the interchange.

For the `PRF` segment, the intent is that `MILLWORK:LIT08-04-23` is the entire `PRF01` element?

**Comment by saravanan-periyasamy03** [comment]
Hi @MikeEdgar ,

Yes. `MILLWORK:LIT08-04-23` is the entire data of PFR01 and we don't want EDIStreamReader to interpret it and throw exception.

`Since the ISA version is 00400, the repetition feature of X12 isn't actually enabled for the interchange.` Are you saying for ISA version 00400 , the repetition will not take any effect?

**Comment by MikeEdgar** [comment]
@saravanan-periyasamy03 , yes repetition will not take effect, but the composite element will be used, which is what you're seeing with `:`. Even then, it shouldn't throw an exception, but rather emit an error event (that you can ignore in this case). 

Can you share a small file that reproduces the exception?

**Comment by saravanan-periyasamy03** [comment]
Hi @MikeEdgar ,

Here is the sample EDI,

`ISA*00*          *00*          *02*ABCB           *01*123456789      *230816*1432*U*00400*111283228*0*P*:~
GS*MM*ABCB*123456789*20230816*1432*283230*X*004010~
ST*866*111300152~
LX*1~
AT8*G*L*830*16~
PRF*230222069~
PRF*WORK:MIT08-04-23~
SE*6*111300152~
GE*1*283230~
IEA*1*111283228~`

Note: We are not having the composite element defined in the schema.

**Comment by MikeEdgar** [comment]
@saravanan-periyasamy03 , I'm not able to reproduce the exception with the test case below. Besides the schema, is there anything else I could be missing? Does this test case produce the exception for you?

```java
@Test
void testIssue383() throws IOException {
    EDIInputFactory factory = EDIInputFactory.newFactory();
    InputStream source = new ByteArrayInputStream((""
            + "ISA*00*          *00*          *02*ABCB           *01*123456789      *230816*1432*U*00400*111283228*0*P*:~ "
            + "GS*MM*ABCB*123456789*20230816*1432*283230*X*004010~ "
            + "ST*866*111300152~ "
            + "LX*1~ "
            + "AT8*G*L*830*16~ "
            + "PRF*230222069~ "
            + "PRF*WORK:MIT08-04-23~ "
            + "SE*6*111300152~ "
            + "GE*1*283230~ "
            + "IEA*1*111283228~").getBytes());
    EDIStreamReader reader = factory.createEDIStreamReader(source);

    try {
        while (reader.hasNext()) {
            switch (reader.next()) {
            case SEGMENT_ERROR:
            case ELEMENT_OCCURRENCE_ERROR:
            case ELEMENT_DATA_ERROR:
                fail("Unexpected error: " + reader.getErrorType());
            default:
                break;
            }
        }
    } catch (Exception e) {
        fail(e);
    } finally {
        reader.close();
    }
}
```

**Comment by MikeEdgar** [comment]
Hi @saravanan-periyasamy03 , please see my earlier comment. I was not able to reproduce the exception and will need some additional information or a test case that demonstrates the problem in order to identify a fix.

**Comment by MikeEdgar** [comment]
@saravanan-periyasamy03 , is this still an issue for you?

**Comment by MikeEdgar** [comment]
Closing for now due to inactivity. Please comment/reopen if this is still a problem.
