### ISSUE TITLE
default decimal mark is point (.) when UNA segment is not present

### ISSUE THREAD

**Issue by Kaiawaia** [xlate/staedi#406]
As mentioned in [this discussion](https://github.com/xlate/staedi/discussions/405) the default decimal mark is point(.) when the UNA segment is not present. This is a problem when you need another decimal mark (e.g. comma) for your locale decimal values.

To reproduce this bug you can delete an UNA segment and replace the decimal points with comma. Add a validation schema with base="decimal" in elementType for the decimal elements. You will get an validation error of type INVALID_CHARACTER_DATA.

**Comment by MikeEdgar** [comment]
@Kaiawaia the fix for this is included in release [1.24.0](https://github.com/xlate/staedi/releases/tag/v1.24.0)

**Comment by Kaiawaia** [comment]
@MikeEdgar the fix is working fine. Thanks for your really fast accomplishment.
