### ISSUE TITLE
How to process large EDI files in reader service

### ISSUE THREAD

**Issue by NandaBalakrishnan** [xlate/staedi#451]
HI @MikeEdgar , 
                    The reader service is unable to process the big edi file, even if we are attempting to process one that is larger than 10MB. Is there a way to manage the large file or is it possible to process it in batches/ chunks?

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan there shouldn't be any difference in how you use the staedi APIs for large versus small files. What is the problem/error you have?

**Comment by NandaBalakrishnan** [comment]
sure @MikeEdgar. Thank you.

**Comment by MikeEdgar** [comment]
@NandaBalakrishnan are you still having an issue with this?

**Comment by MikeEdgar** [comment]
Closing for now, please reopen if there is a problem still occurring.
