### ISSUE TITLE
dots in an element in the ISA results in ELEMENT_OCCURRENCE_ERROR

### ISSUE THREAD

**Issue by cpotter1** [xlate/staedi#463]
```ISA*00*..........*00*..........*ZZ*               *ZZ*               *130510*1147*^*00501*111114280*0*P*:~```

The above results in an error. Seems like dots/periods should be valid and not result in an error.

**Comment by MikeEdgar** [comment]
Thanks for the issue @cpotter1. The parser has been skipping the decimal separator since the beginning, but I don't think there's a valid reason for it. PR #464 removes that.

**Comment by MikeEdgar** [comment]
Fixed in release [1.25.1](https://github.com/xlate/staedi/releases/tag/v1.25.1)
