### ISSUE TITLE
Validation of edifact fails when an empty segment starts a loop in an implementation schema

### ISSUE THREAD

**Issue by benisantos** [xlate/staedi#79]
If the empty segment is removed (from schemas and edifact file), the validation works perfectly. Same if the empty segment is moved to second or following positions in the loop.

A failed test is attached.

[empty-segment-loop-validation.zip](https://github.com/xlate/staedi/files/5033161/empty-segment-loop-validation.zip)

**Comment by MikeEdgar** [comment]
@benisantos , thank you for the test case. This will be prioritized over the other issue related to the repetition delimiter.

**Comment by MikeEdgar** [comment]
@benisantos - please try version `1.9.4`. It was pushed to Maven Central around 8:20 PM EDT and should be available to use in your POM shortly after.

**Comment by benisantos** [comment]
Thank you so much @MikeEdgar. That error was fixed!

Now, I think I have other problems with the implementation schema, but I need to debug more...
