### ISSUE TITLE
EDIFACT Interactive Messages

### ISSUE THREAD

**Issue by MikeEdgar** [xlate/staedi#8]
Add support for EDIFACT interactive interchanges and messages. These are those interchanges identified by the `UIH` header segment.

Please comment on this issue if this feature is important to you.

**Comment by softmade-timobruentjen** [comment]
Havent´t seen so far. Is it possible for you to add an example to the wiki pages for a regular UN-EDIFACT Message like INVOIC? I stumbled to the code to get it running, maybe others won´t have to. I can send you my example to take it over to the wiki pages?

**Comment by MikeEdgar** [comment]
@softmade-timobruentjen - I would be happy to add to the wiki and if you have an example that would be great. Are you using a validation schema for INVOIC as well?

**Comment by softmade-timobruentjen** [comment]
Well, i´ve use the one given by StAEDI. It was very strictly against errors ;-) in the EDIFACT Code.

Here is what i´ve done to get the main EDI Part running for INVOIC 96A Standard:
`      // (1) Create an EDIOutputFactory
        EDIOutputFactory factory = EDIOutputFactory.newFactory();

        // (2) Optionally specify delimiters - here the given values are the same as default
        factory.setProperty(EDIStreamConstants.Delimiters.SEGMENT, '\'');
        factory.setProperty(EDIStreamConstants.Delimiters.DATA_ELEMENT, '+');
        factory.setProperty(EDIStreamConstants.Delimiters.COMPONENT_ELEMENT, ':');
        factory.setProperty(EDIStreamConstants.Delimiters.RELEASE, '?');
        factory.setProperty(EDIStreamConstants.Delimiters.REPETITION, ' ');
        
        // Write each segment on a new line
        //factory.setProperty(EDIOutputFactory.PRETTY_PRINT, true);

        // (3) Create an EDIStreamWriter. Any OutputStream may be used - here we are writing to a file
        OutputStream stream = null;
		try {
			stream = new FileOutputStream("someFileNameYouPrefer");
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        EDIStreamWriter writer = factory.createEDIStreamWriter(stream);

        // (4) Start the interchange
        writer.startInterchange();

        // (5) Write the three segments necessary for the INVOIC (UNA, UNB, UNH)
        writer.writeStartSegment("UNA").writeEndSegment();
		
        writer.writeStartSegment("UNB");
        writer.writeStartElement().writeElementData("UNOC");
        writer.writeEmptyComponent().writeComponent("3");
        writer.endElement();
        writer.writeStartElement().writeElementData("0123456789012");
        writer.writeEmptyComponent().writeComponent("14");
        writer.endElement();
        writer.writeStartElement().writeElementData("0123456789012");
        writer.writeEmptyComponent().writeComponent("14");
        writer.endElement();
        writer.writeStartElement().writeElementData("200702");
        writer.writeEmptyComponent().writeComponent("0734");
        writer.endElement();
        writer.writeStartElement().writeElementData("00000563").endElement();
        writer.writeEndSegment();
        
        writer.writeStartSegment("UNH");
        writer.writeStartElement().writeElementData("0001").endElement();
        writer.writeStartElement().writeElementData("INVOIC");
        writer.writeEmptyComponent().writeComponent("D");
        writer.writeComponent("96A");
        writer.writeComponent("UN");
        writer.writeComponent("EAN008");
        writer.endElement();
        writer.writeEndSegment();
        
        //Begin Message BGM
        writer.writeStartSegment("BGM");
        writer.writeStartElement().writeElementData("380").endElement();
        writer.writeStartElement().writeElementData("1676245").endElement();
        writer.writeStartElement().writeElementData("9").endElement();
        writer.writeEndSegment();

       //From Here do further INVOIC related segments like DTM and so on

     // (6) End the interchange
        writer.endInterchange();

        // (7) Close the EDIStreamWriter. This must be done to ensure the output is written
        writer.close();`

**Comment by MikeEdgar** [comment]
@softmade-timobruentjen - thank you for the example. I've added it to the Wiki with some modifications: https://github.com/xlate/staedi/wiki/Writing-EDI-Data-(Simple)#edifact-example. Please take a look at how the composite elements are written. That may simplify your process. As always, please open up a new issue if you have any problems. Thanks

**Comment by softmade-timobruentjen** [comment]
Great Work, Thanks

**Comment by MikeEdgar** [comment]
Closing this issue for now due to lack of interest for EDIFACT interactive messages. This may be revisited in the future if there is interest.
