### ISSUE TITLE
Get Description from Reference Code

### ISSUE THREAD

**Issue by hod-github** [xlate/staedi#82]
Hi, looking for a way to get the Description of an Element from its Reference Code.

1) I'm parsing an 837 file and want to know if I can get the element description from the reference code (reader.getReferenceCode())
In other words, is there a way for me to get (as an example) "Organization Name" from "NM103"?

2) Same question with Loops, how can I get (as an example) "1000B" from "L0001"?

Thanks in advance.

**Comment by MikeEdgar** [comment]
@hod-github - version `1.10.0` has been released with this change included. The `reference` returned by the `EDIStreamReader` will vary depending on the position of the reader within the input EDI stream.

```java
EDIReference reference = reader.getSchemaTypeReference();
EDIType type = reference.getReferencedType();
String title = type.getTitle(); // "title" attribute from schema
String description = type.getDescription(); // "description" element text from schema
```

**Comment by hod-github** [comment]
Wow, that was fast!! Do you mind adding a quick snapshot of how it looks like in the Schema xml? Just to I'm sure I'm going to use it correctly.

**Comment by MikeEdgar** [comment]
@hod-github - you would set the `title` similar to the elements in the common X12 control schema:

https://github.com/xlate/staedi/blob/master/src/main/resources/X12/common.xml

Just to be clear, this addresses only the first item in the original issue description. The second point about `1000B` vs. `L0001` is already covered. You just need to set the `code` attributes on your loops accordingly.

**Comment by hod-github** [comment]
Greatly appreciate it!! Thanks a bunch.

**Comment by hod-github** [comment]
Hi @MikeEdgar , while trying to use the new functionality I realized I probably have some gap in my understanding. So wanted to ask this quick question to see where I'm going wrong...
The description and title of an element might change depending on the position of it in the file, for example if I have this (simplified) file:
ISA*01*...
GS*HC*...
ST*837*...
BHT*0019*...
**NM1*41*2*SAMPLE INC*****46*496103**
PER*IC*...
**NM1*40*2*PPO BLUE*****46*54771**
.
.

You can see that I have two NM1 and both are the exact same structure, yet each one represents a different meaning, the first NM1 is "**Submitter Name**" while the second if the "**Receiver name**", how do I use the schema to associate a different title for each one so when I'm in line 5 the getTitle() will return "**Submitter Name**" and in line 7 "**Receiver name**"?

**Comment by MikeEdgar** [comment]
@hod-github - consider the following "standard" layout (everything after loop 1000 is omitted to make the point).

```xml
  <transaction>
    <sequence>
      <segment type="BHT" minOccurs="1"/>
      <segment type="REF" maxOccurs="3"/>
      <loop code="1000" maxOccurs="10">
        <sequence>
          <segment type="NM1"/>
          <segment type="N2" maxOccurs="2"/>
          <segment type="N3" maxOccurs="2"/>
          <segment type="N4"/>
          <segment type="REF" maxOccurs="2"/>
          <segment type="PER" maxOccurs="2"/>
        </sequence>
      </loop>
      ...
    </sequence>
  </transaction>
```
While the standard defines the generic layout of the transaction, the implementation defines what multiple occurrences of a loop should look like. For example, loop 1000A and 1000B are both occurrences of the standard loop 1000, with a reduction in the segments and elements that can be used. This roughly describes those two loops in the 837, again with the remainder of the implementation after loop 1000 omitted. Note the `discriminator` attribute which names the element within the loop's first segment that is used to determine which of the occurrences to select for validation. In the case of loop 1000, the NM101 is either 41 or 40 (identified in the element enumeration in position 1). Segments that are not to be used at left out of the implementation.

```xml
  <implementation>
    <sequence>
      <segment type="BHT" />
      <loop code="1000A" type="1000" discriminator="1">
        <sequence>
          <segment type="NM1" title="Submitter Name">
            <sequence>
              <element position="1">
                    <enumeration>
                      <value>41</value>
                    </enumeration>
              </element>
              <element position="2"/>
              <element position="3"/>
              <element position="4"/>
              <element position="5"/>
              <element position="8"/>
              <element position="9"/>
            </sequence>
          <segment>
          <segment type="PER" />
        </sequence>
      </loop>
      <loop code="1000B" type="1000" discriminator="1">
        <sequence>
          <segment type="NM1" title="Receiver Name">
            <sequence>
              <element position="1">
                    <enumeration>
                      <value>40</value>
                    </enumeration>
              </element>
              <element position="2"/>
              <element position="3"/>
              <element position="8"/>
              <element position="9"/>
            </sequence>
          <segment>
        </sequence>
      </loop>
    </sequence>
  </implementation>
```
